option(BUILD_SHARED_LIBS "Build shared library" OFF)
set(FAUXBOY_BUILD_SHARED "${BUILD_SHARED_LIBS}")
mark_as_advanced(FAUXBOY_BUILD_SHARED)

option(BUILD_TESTING "Build tests" OFF)
set(FAUXBOY_BUILD_TESTS "${BUILD_TESTING}")
mark_as_advanced(FAUXBOY_BUILD_TESTS)

set(FAUXBOY_BUILD_TYPE STATIC)
if (FAUXBOY_BUILD_SHARED)
    set(FAUXBOY_BUILD_TYPE SHARED)
endif ()